# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'typerium_mobile' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'CxxBridge', # Include this for RN >= 0.47
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  # pod 'FBSDKCoreKit'
  # pod 'FBSDKLoginKit'
  # pod 'FBSDKShareKit'
  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end

