export default {
  SHOW_DRAWER_LEFT: 'SHOW_DRAWER_LEFT',
  SHOW_DRAWER_RIGHT: 'SHOW_DRAWER_RIGHT',
  SHOW_TABS: 'SHOW_TABS',
  SET_SCREEN: 'SET_SCREEN',
  SET_SCREEN_DATA: 'SET_SCREEN_DATA',
  CHANGE_SCREEN: 'CHANGE_SCREEN',
  CREATE_PHOTO: 'CREATE_PHOTO',
};
