export default {
  SHOW_PHONE_CODES: 'SHOW_PHONE_CODES',
  SET_PHONE_CODE: 'SET_PHONE_CODE',
  SHOW_RESET_PASSWORD: 'SHOW_RESET_PASSWORD',
  SHOW_OFFLINE: 'SHOW_OFFLINE',
  SHOW_SELECTION: 'SHOW_SELECTION',
  SET_SELECTION_DATA: 'SET_SELECTION_DATA',
  SET_SELECTION: 'SET_SELECTION',
};
